const data = {
    products:[
        {
            _id: '1',
            name: 'Painting 1',
            category: 'art',
            image: './images/prod1.jpg',
            price: 120,
            brand: 'impressionism',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: '2',
            name: 'Painting 2',
            category: 'art',
            image: './images/prod2.jpg',
            price: 100,
            brand: 'impressionism',
            rating: 4,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: '3',
            name: 'Painting 3',
            category: 'art',
            image: './images/prod3.jpg',
            price: 1200,
            brand: 'impressionism',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: '4',
            name: 'Painting 4',
            category: 'art',
            image: './images/prod4.jpg',
            price: 10,
            brand: 'impressionism',
            rating: 4.5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: '5',
            name: 'Painting 5',
            category: 'art',
            image: './images/prod5.jpg',
            price: 18000,
            brand: 'impressionism',
            rating: 5,
            numReviews: 10,
            description: "high quality product",
        },
        {
            _id: '6',
            name: 'Painting 6',
            category: 'art',
            image: './images/prod6.jpg',
            price: 150,
            brand: 'impressionism',
            rating: 4.8,
            numReviews: 10,
            description: "high quality product",
        },
    ]
}

export default data;